### ISSUE TITLE
Can't find setuptools ver

### ISSUE THREAD

**Issue by 3rdaiohpin** [kit4py/Streamify#2]
Could not find a version that satisfies the requirement setuptools~=65.5.1 (from versions: none)
ERROR: No matching distribution found for setuptools~=65.5.1

**Comment by 3rdaiohpin** [comment]
Nevermind fixed that issue now I'm getting this after running python3_main_new.py:Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Streamify/Streamify/user_setup.py", line 1, in <module>
    import tkinter as tk                              ModuleNotFoundError: No module named 'tkinter' as well as this error:Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Streamify/Streamify/main_new.py", line 164, in <module>
    task = int(input('\033[93m' + '''Choose task:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by 3rdaiohpin** [comment]
Now I get these two errors after entering python3_main_new.py:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Streamify/Streamify/user_setup.py", line 1, in <module>
    import tkinter as tk                              ModuleNotFoundError: No module named 'tkinter'        Choose task:
[1] play
[2] create accounts
[3] create & play
Enter number: Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Streamify/Streamify/main_new.py", line 164, in <module>
    task = int(input('\033[93m' + '''Choose task:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
